#!/bin/bash

db_user=bolt
db_name=bolt
root_pwd=$(sudo cat /etc/yunohost/mysql)
domain=$(sudo yunohost app setting bolt domain)

mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"
sudo rm -rf /var/www/bolt
sudo rm -f /etc/nginx/conf.d/$domain.d/bolt.conf
